### ISSUE TITLE
Laravel 5 support

### ISSUE THREAD

**Issue by dinajpuri** [bradcornford/Backup#1]
Hello,

Do you've any plan for laravel 5 support?

Regards

**Comment by bradcornford** [comment]
Hi there,

Yes, I'm just making sure the package is stable before I bring in Laravel 5 support. There isn't a massive amount of change needed for the version bump either.

One thing i'm looking into beforehand is a way to locate the executables for each export/restore commands programatically to reduce the need for configuration.

**Comment by bradcornford** [comment]
I've pushed up support for Laravel 5 to the develop branch if you would like to test it.
