### ISSUE TITLE
"The system cannot find the path specified.\r\n"

### ISSUE THREAD

**Issue by etlanda24** [bradcornford/Backup#10]
im not sure what is wrong, here is my controller, i've created many folder as the path, but nothing works

$base = 'uploads';
Backup::setPath($base);
Backup::export();
dd(Backup::getProcessOutput());

**Comment by bradcornford** [comment]
Hi there,

Ensure that the folder has read/write permissions. I would use something like `..app/storage/backup/`.

The following should work as expected:

```php
Backup::setPath(public_path());

Backup::export();
```

**Comment by bradcornford** [comment]
Hi there,

Can you try giving the package a full path, for example: `/tmp`
