### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by jcsoriano** [bradcornford/Backup#12]
Hi, thank you for the wonderful package! Just wanted to ask if you could add support for Laravel 6.0. Currently getting the following error:

![image](https://user-images.githubusercontent.com/5937317/65047573-43a8c800-d995-11e9-8264-7f55daf7ba50.png)

Likely because of this:
![image](https://user-images.githubusercontent.com/5937317/65047533-312e8e80-d995-11e9-9cf5-235f7bd6f1f9.png)

**Comment by bradcornford** [comment]
Hi @jcsoriano,

I've now added support for Laravel 6 to this project in current version 2.6.0.
