### ISSUE TITLE
Class 'Cornford\Backup\Facades\Backup' not found

### ISSUE THREAD

**Issue by sandeepgajera** [bradcornford/Backup#13]
HI

After setup completed it  when i can export method it give me error :

Class 'Cornford\Backup\Facades\Backup' not found

![image](https://user-images.githubusercontent.com/50587186/71668871-abdab880-2d90-11ea-9b84-9e5da7cf929e.png)

Can You please help me.

Thanks&Regards

**Comment by bradcornford** [comment]
Hi there,

Can you confirm you've added the class alias to app/config/app.php?

```
'Backup'         => Cornford\Backup\Facades\Backup::class,
```

**Comment by sandeepgajera** [comment]
Hi,

Yes I have already added in config/app.php

![image](https://user-images.githubusercontent.com/50587186/71724398-2d484e80-2e56-11ea-8314-aeb4845c6e47.png)

Can you please help me.

**Comment by bradcornford** [comment]
Can you change the value to be `Cornford\Backup\Facades\Backup::class`

**Comment by sandeepgajera** [comment]
HI

I set in config but still same issue.

![image](https://user-images.githubusercontent.com/50587186/71724771-8664b200-2e57-11ea-83a7-281b2161c2c8.png)

**Comment by bradcornford** [comment]
Can you show me the calling code? Another option is to add a use statement:

```
use Cornford\Backup\Facades\Backup;
```

**Comment by bradcornford** [comment]
Have you also run `composer dump-autoload -o`?

**Comment by sandeepgajera** [comment]
Hi

Yes now working thanks Men
