### ISSUE TITLE
Database is not imported.

### ISSUE THREAD

**Issue by wmlab03** [bradcornford/Backup#6]
Hello, I have installed successfully via composer and publish vendor files. When I am trying to import database, nothing happens. No files are created under backup directory.

Here is my controller file.

<?php
namespace App\Http\Controllers;
use Backup;
class PagesController extends Controller
{
public function test(){
        Backup::export();
}
}

Route.php
get('/test','MyController@test');

I have also checked database.php file and put database configuration which is accessible.
I am getting blank results all the time.

**Comment by bradcornford** [comment]
Hi there,

The export method returns a boolean for the status of the export. I would assume this has returned false if nothing has been created.

Ensure the directory for backups exists "app/storage/backup" and has relevant read and write permissions.

Out if interest, which database driver are you using?

**Comment by wmlab03** [comment]
Here is my database.php file.

<?php
return [
    'fetch' => PDO::FETCH_CLASS,
    'default' => 'primary',
    'connections' => [
        'primary' => [
            'driver'    => 'mysql',
            'host'      => 'localhost',
            'database'  => 'testing',
            'username'  => 'root',
            'password'  => '1234',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
            'strict'    => false,
        ],
    ],
    'migrations' => 'migrations',
];

I have checked that folder exists and I tried dd(Backup::export()) which is return false. I am using it in localhost wamp version 2.5 with PHP version 5.6.12 and laravel 5.1

**Comment by bradcornford** [comment]
Okay, the configuration looks fine.

It may be that the export process cant find the mysqldump process as your running Windows. If you go to "control pannel" -> "system and security" -> "system" -> "advanced system settings" -> "environment varaibles". Then find "Path" in the "system variables" section, press "edit", then press "new", then paste the location to wamps mysql bin folder, for example mine is "C:\wamp\bin\mysql\mysql5.6.17\bin". Then press "ok", then press "ok", then press "apply", then press "okay". If you then run "command prompt", then type "mysqldump", and press enter, you should some information about how to run mysqldump.

Also can you run, and send me the output:

```php

Backup::export();
dd(Backup::getProcessOutput());

```
