### ISSUE TITLE
Unable to export to path "" as it doesn't exist

### ISSUE THREAD

**Issue by benj-popoi22** [bradcornford/Backup#7]
#5 but the path is configured already. path set to public_path(). even when getWorkingFilepath the result is null. BTW i'm using laravel 5.2

**Comment by bradcornford** [comment]
Hi there,

So what have you set in your configuration file? For path? Is the path writable and readable by the web user?

**Comment by bradcornford** [comment]
Just seen the issue myself on Windows, I've pushed a fix up to the develop branch if you want to give it a go.

**Comment by bradcornford** [comment]
The fix has been pushed to current versions v2.4.0/1.3.0.
