### ISSUE TITLE
Backup::export('database_backup'); always returned false

### ISSUE THREAD

**Issue by whiters007** [bradcornford/Backup#8]
Hi,

i have some problem when i used this function : 

`Backup::export('database_backup'); or Backup::export('');`

i always get `null` returned

can you guys help me? please
Thanks 👍

**Comment by bradcornford** [comment]
Hi there,

Could you run the following and send me the response:

```php
Backup::export('database_backup');
dd(Backup::getProcessOutput());
```

**Comment by whiters007** [comment]
thanks for your reply @bradcornford ,

i've got response like this : `"The system cannot find the path specified.\r\n"`

but if i checked again in App/Backup.php, i think i'm in right way, `'path' => '../storage/backup/',`

and also, i checked too my folder structure,

![folder_structure](https://cloud.githubusercontent.com/assets/20394899/23194149/0691ea8a-f8df-11e6-87c1-f0b577f39395.png)

did i miss or understanding something ??

**Comment by bradcornford** [comment]
Hi there,

Can you confirm that you have provided absolute paths to your processors configuration array for the mysql key. If not, add the mysql/mysqldump executables to your PATH, see for more information: http://www.computerhope.com/issues/ch000549.htm. For example:

```php
	'processors' => array(
		'mysql' => array(
			'export' => '/usr/local/mysql/bin/',
			'restore' => '/usr/local/mysql/bin/'
		),
       ...
```

Also, it may help to provide an absolute path for the path configuration variable too. For example:

```php
    'path' => '/var/www/laravel/storage/backup/',
```

**Comment by MikePowell1** [comment]
Hi @bradcornford , actually I had some problem like @whiters007 too,
my configuration totally just like @whiters007  too, but since I saw your comment, I truly miss understanding, I tried to open your link, and also I tried to create a new variable but I confused to fill in environtment setting...

do you mind to give me very clearly instruction about this environtment setting and also `Backup.'processor' array()` too ?

for example my project is in `C:xampp/htdocs/myproject/...`
so which PATH I should choose for environtment settings ??

or do you mind to give me your screenshoot envinrontment setting (including the PATH) and the `'processor'=>array() ` too..

thanks  
![environtment](https://cloud.githubusercontent.com/assets/25955591/23212927/7aa7e288-f93b-11e6-96ea-ea14cbe7b522.png)

**Comment by bradcornford** [comment]
Hi there,

Within the backup.php configuration file, there is an array item with the key 'processors', this can be manually set to define the location of the mysql (for restore)/mysqldump (for export) binaries, for example:

```php
	/*
	|--------------------------------------------------------------------------
	| Database Engine Processors
	|--------------------------------------------------------------------------
	|
	| Set the database engines processor location, trailing slash is required.
	|
	*/
	'processors' => array(
		'mysql' => array(
			'export' => 'g:\wamp\bin\mysql\mysql5.6.17\bin\',
			'restore' => 'g:\wamp\bin\mysql\mysql5.6.17\bin'
		),
		'pqsql' => array(
			'export' => '/usr/bin/',
			'restore' => '/usr/bin/'
		),
		'sqlite' => array(
			'export' => null,
			'restore' => null
		),
		'sqlsrv' => array(
			'export' => '/usr/bin/',
			'restore' => '/usr/bin/'
		),
	),
```

As for the 'Path' variable, this is utilised by the system to allow it to find extra binaries/executables.

Follow the below steps as an example to adding a new path variables, amended the path to your own binaries:

System -> Advanced system settings -> Environment Variables... ->System variables -> Path -> Edit... -> New -> "g:\wamp\bin\mysql\mysql5.6.17\bin\"

![capture](https://cloud.githubusercontent.com/assets/2913887/23330571/1b9ea83e-fb49-11e6-8330-8b835f04d50c.PNG)

**Comment by whiters007** [comment]
Hi @bradcornford , thanks for your reply & your kindness... working prefectly, god bless you :D
also thanks to @MikePowell1 , to describe my problem very clearly  :D

**Comment by MikePowell1** [comment]
well that's not a problem @whiters007 , but I still have a questions for @bradcornford , this backup database is directly in added in `'path' => 'myfolder'` , but is it possibly to download it first ?, so users can be choose the folder what they want... it looks like you export data directly from phpmyadmin, it download it first right??

please help me :D 
thanks

**Comment by bradcornford** [comment]
Hi there,

You will have to export the database first, to a temp directory or something, after which you could then use something like the below to allow force a browser to download the file. Something like the below should work:

```php
        Backup::setCompress(false);
        Backup::setPath(sys_get_temp_dir());

        $backupFileExtension = 'sql';
        $backupFilename = 'database_backup' . '.' . $backupFileExtension;
        $backupFilePath = Backup::getPath() . '/' . $backupFilename;

        Backup::export($backupFilename);

        header("Content-Type: application/sql");
        header("Content-Transfer-Encoding: Binary");
        header("Content-Disposition: attachment; filename=\"{$backupFilename}\"");

        echo readfile($backupFilePath);

        unlink($backupFilePath);
```

**Comment by MikePowell1** [comment]
hi, @bradcornford ... I really appreciate what are you doing to help me... it's working very well, thanks dude, i'll never forget your help :D

**Comment by hcweb** [comment]
Hello, Will php7.2+laravel5.6 be used?

**Comment by bradcornford** [comment]
Hi there, 

The package should work with PHP 7.2 and Laravel 5.6. However i haven't tested it myself.

**Comment by hcweb** [comment]
Okay, thank you very much. I'll try it first. What's my feedback?
