### ISSUE TITLE
mysqldump: Got error: 2004: Can't create TCP/IP socket (10106) when trying to connect

### ISSUE THREAD

**Issue by hcweb** [bradcornford/Backup#9]
hi   `\Backup::setPath(public_path());
        \Backup::export('xtn');
        dd(\Backup::getProcessOutput());`

mysqldump: Got error: 2004: Can't create TCP/IP socket (10106) when trying to connect

What should I do?

Can give a complete use case, thank you!

**Comment by bradcornford** [comment]
Hi there,

Ensure that you have your database settings stored within your config/database.php, for example:

```
		'mysql' => array(
			'driver'    => 'mysql',
			'host'      => 'localhost',
			'database'  => 'test',
			'username'  => 'root',
			'password'  => '',
			'charset'   => 'utf8',
			'collation' => 'utf8_unicode_ci',
			'prefix'    => '',
		),
```

The following should work as expected:

```php
            Backup::setPath(public_path());

            Backup::export();
```

**Comment by fa134624** [comment]
i have the same error

**Comment by bradcornford** [comment]
Can you give me some more info by giving me the output from the following:

```Backup::getProcessOutput();```

**Comment by alvaro259818** [comment]
I have the same problem 
This is the output of this Backup::getProcessOutput() :

"mysqldump.exe: Got error: 2004: "Can't create TCP/IP socket (10106 "Unknown error")" when trying to connect"

**Comment by bradcornford** [comment]
It appears to be a bug itself with mysqldump, see: https://bugs.mysql.com/bug.php?id=53682
